apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeW5ld2Rldi5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiUmVnaXN0cnlOZXdEZXYiLCJwYXNzd29yZCI6IjhvUUkwbUxLY3k9RnZsaWZKTllNMURrNTFycnl4MVl3IiwiZW1haWwiOiJpbmZyYWVzdHJ1Y3R1cmFAcmVudGluZ2NvbG9tYmlhLmNvbSIsImF1dGgiOiJVbVZuYVhOMGNubE9aWGRFWlhZNk9HOVJTVEJ0VEV0amVUMUdkbXhwWmtwT1dVMHhSR3MxTVhKeWVYZ3hXWGM9In19fQ==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{".dockerconfigjson":"eyJhdXRocyI6eyJyZWdpc3RyeW5ld2Rldi5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiUmVnaXN0cnlOZXdEZXYiLCJwYXNzd29yZCI6IjhvUUkwbUxLY3k9RnZsaWZKTllNMURrNTFycnl4MVl3IiwiZW1haWwiOiJpbmZyYWVzdHJ1Y3R1cmFAcmVudGluZ2NvbG9tYmlhLmNvbSIsImF1dGgiOiJVbVZuYVhOMGNubE9aWGRFWlhZNk9HOVJTVEJ0VEV0amVUMUdkbXhwWmtwT1dVMHhSR3MxTVhKeWVYZ3hXWGM9In19fQ=="},"kind":"Secret","metadata":{"annotations":{},"name":"secretregistry","namespace":"development"},"type":"kubernetes.io/dockerconfigjson"}
  creationTimestamp: "2024-06-18T23:12:49Z"
  labels:
    velero.io/backup-name: day-20240618205327
    velero.io/restore-name: day-20240618205327-20240618181216
  name: secretregistry
  namespace: elasticsearch
  resourceVersion: "151211933"
  uid: 2c94cc0d-6072-4f88-acff-f12fbf3cc224
type: kubernetes.io/dockerconfigjson
