apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin
  namespace: mauriciovelez
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: admin.mauricioveleznumerologo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 80
  tls:
    - hosts:
        - admin.mauricioveleznumerologo.com
      secretName: admin-mauricioveleznumerologo-tls
